# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.3972, 0.5936, 0.1014, 0.3907, 0.2189, 0.9721, 0.3886],
        [0.4966, 0.6859, 0.8764, 0.8825, 0.5528, 0.5922, 0.4465],
        [0.4345, 0.7232, 0.0823, 0.5089, 0.1604, 0.4531, 0.3404],
        [0.6362, 0.2488, 0.0868, 0.1871, 0.5680, 0.9008, 0.8423],
        [0.2070, 0.1893, 0.3888, 0.5460, 0.1738, 0.0758, 0.8957],
        [0.2426, 0.3481, 0.9302, 0.8541, 0.1027, 0.6512, 0.0591],
        [0.6983, 0.4832, 0.6461, 0.4685, 0.7355, 0.8753, 0.4333]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random_tensor2 = torch.rand(1,7)
# Perform matrix multiplication 

mat_mul = torch.matmul(random_tensor, random_tensor2.T)
mat_mul

tensor([[1.7848],
        [2.8780],
        [1.6271],
        [2.2279],
        [1.8703],
        [2.0649],
        [2.6802]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
random_tensor3 = torch.rand(7,7)
random_tensor4 = torch.rand(1,7)

# Matrix multiply tensors
random_tensor3 @ random_tensor4.T


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU"
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
device = "cuda:1" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
gpu_tensor1 = torch.rand(2,3).to(device)
gpu_tensor2 = torch.rand(2,3).to(device)
print(gpu_tensor1)
print(gpu_tensor1.shape)
print(gpu_tensor2)
print(gpu_tensor2.shape)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:1')
torch.Size([2, 3])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:1')
torch.Size([2, 3])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
# Perform matmul on tensor_A and tensor_B
mat = gpu_tensor1 @ gpu_tensor2.T
mat

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:1')

### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
print(torch.max(mat))
# Find min
print(mat.min())

tensor(0.5617, device='cuda:1')
tensor(0.3647, device='cuda:1')


### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
max_idx = torch.argmax(mat)

# Find arg min
min_idx = torch.argmin(mat)
max_idx, min_idx

(tensor(3, device='cuda:1'), tensor(0, device='cuda:1'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [15]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor1 = torch.rand(1,1,1,10)

# Remove single dimensions
tensor1_squeezed = tensor1.squeeze()

# Print out tensors and their shapes
print(tensor1, tensor1.shape)
print(tensor1_squeezed, tensor1_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
