In [2]:
import torch

In [3]:
!nvidia-smi

Mon Dec 23 22:34:07 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1080 Ti     Off | 00000000:60:00.0 Off |                  N/A |
|  0%   38C    P8              17W / 250W |      9MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Checking GPU access using `pytorch`

In [2]:
# checking gpu
import torch
torch.cuda.is_available()

True

In [13]:
device = "cuda:1" if torch.cuda.is_available() else "cpu"
device

'cuda:1'

In [6]:
# COUNT NUMER OF  GPUTS
torch.cuda.device_count()

6

In [24]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(2444,3444)
tensor.shape, tensor.device

(torch.Size([2444, 3444]), device(type='cpu'))

In [25]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.shape, tensor_on_gpu.device

(torch.Size([2444, 3444]), device(type='cuda', index=1))

In [26]:
%%time
rst = tensor @ tensor.T
rst.shape


CPU times: user 1.06 s, sys: 122 ms, total: 1.18 s
Wall time: 43.2 ms


torch.Size([2444, 2444])

In [31]:
%%time 
rst = tensor_on_gpu@ tensor_on_gpu.T
rst.shape

CPU times: user 793 µs, sys: 903 µs, total: 1.7 ms
Wall time: 1.31 ms


torch.Size([2444, 2444])

In [45]:
tensor_cpu = tensor_on_gpu.to("cpu").numpy()
tensor_cpu.shape, tensor_cpu.dtype

((2444, 3444), dtype('float32'))

## understanding squeeze and unsqueeze again

In [1]:
import torch

In [4]:
a = torch.randint(10,20,(1,9))
a, a.shape

(tensor([[17, 12, 12, 19, 13, 14, 18, 12, 10]]), torch.Size([1, 9]))

In [7]:
s = a.squeeze()
s , s.shape, s.ndim

(tensor([17, 12, 12, 19, 13, 14, 18, 12, 10]), torch.Size([9]), 1)

In [8]:
a = torch.randint(10,20,(1,9,4,1))
a, a.shape

(tensor([[[[17],
           [16],
           [17],
           [13]],
 
          [[14],
           [12],
           [18],
           [13]],
 
          [[14],
           [14],
           [16],
           [14]],
 
          [[19],
           [13],
           [18],
           [12]],
 
          [[19],
           [17],
           [14],
           [15]],
 
          [[19],
           [15],
           [15],
           [17]],
 
          [[12],
           [10],
           [15],
           [11]],
 
          [[13],
           [12],
           [16],
           [18]],
 
          [[16],
           [14],
           [13],
           [10]]]]),
 torch.Size([1, 9, 4, 1]))

In [9]:
s = a.squeeze()
s, s.shape

(tensor([[17, 16, 17, 13],
         [14, 12, 18, 13],
         [14, 14, 16, 14],
         [19, 13, 18, 12],
         [19, 17, 14, 15],
         [19, 15, 15, 17],
         [12, 10, 15, 11],
         [13, 12, 16, 18],
         [16, 14, 13, 10]]),
 torch.Size([9, 4]))